spring:
  datasource:
    url: jdbc:mysql://pre-project-database.cssa0kfaixyu.ap-northeast-2.rds.amazonaws.com/overflow?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
jwt:
  key: "stackoverflowpreprojectseb45013013013013013013"
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 360